services:
  web:
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - backend_net

  db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - backend_net

  nginx:
    image: nginx:latest
    depends_on:
      - web
    networks:
      - backend_net

networks:
  backend_net:
    driver: bridge