services:
  web:
    command: gunicorn -k uvicorn.workers.UvicornWorker app.main:app -b 0.0.0.0:8000 --workers 4
    restart: always
    image: ghcr.io/vitalyionov/learn-language-server:${IMAGE_TAG:-latest}
    volumes:
      - ./static/images:/app/static/images
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend_net

  db:
    image: postgres:15
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - backend_net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h 127.0.0.1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - certbot-www:/var/www/certbot
      - letsencrypt:/etc/letsencrypt
    depends_on: [web]
    networks:
      - backend_net

networks:
  backend_net:
    driver: bridge

volumes:
  pg_data: { }
  certbot-www: { }
  letsencrypt: { }