"""empty message

Revision ID: 0c75eedf19d0
Revises: 87a13362d2ba
Create Date: 2025-10-08 13:00:09.260999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c75eedf19d0'
down_revision: Union[str, Sequence[str], None] = '87a13362d2ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('translated_text', sa.String(), nullable=False),
    sa.Column('lang_from', sa.String(), nullable=False),
    sa.Column('lang_to', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translations_lang_from'), 'translations', ['lang_from'], unique=False)
    op.create_index(op.f('ix_translations_lang_to'), 'translations', ['lang_to'], unique=False)
    op.create_index(op.f('ix_translations_text'), 'translations', ['text'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_translations_text'), table_name='translations')
    op.drop_index(op.f('ix_translations_lang_to'), table_name='translations')
    op.drop_index(op.f('ix_translations_lang_from'), table_name='translations')
    op.drop_table('translations')
    # ### end Alembic commands ###
