"""empty message

Revision ID: 0dc212aabd1d
Revises: 8c98cb46360b
Create Date: 2026-02-18 11:41:39.197115

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0dc212aabd1d"
down_revision: Union[str, Sequence[str], None] = "8c98cb46360b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    languagecode = sa.Enum("EN", "ES", name="languagecode")
    languagecode.create(op.get_bind(), checkfirst=True)
    op.add_column("definitions", sa.Column("language", languagecode, server_default="ES", nullable=True))
    op.drop_index(op.f("ix_definitions_type"), table_name="definitions")
    op.add_column("meanings", sa.Column("language", languagecode, server_default="ES", nullable=True))
    op.add_column("users", sa.Column("interface_lang", sa.String(), server_default="ru", nullable=False))
    op.drop_column("users", "lang")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("lang", sa.VARCHAR(), server_default=sa.text("'ru'::character varying"), autoincrement=False, nullable=False)
    )
    op.drop_column("users", "interface_lang")
    op.drop_column("meanings", "language")
    op.create_index(op.f("ix_definitions_type"), "definitions", ["type"], unique=False)
    op.drop_column("definitions", "language")
    sa.Enum(name="languagecode").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
