"""empty message

Revision ID: 0f95640c7525
Revises: 0c75eedf19d0
Create Date: 2025-10-08 16:18:42.523338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f95640c7525'
down_revision: Union[str, Sequence[str], None] = '0c75eedf19d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('translations', sa.Column('context', sa.String(), nullable=True))
    op.create_index(op.f('ix_translations_context'), 'translations', ['context'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_translations_context'), table_name='translations')
    op.drop_column('translations', 'context')
    # ### end Alembic commands ###
