"""add is_valid to translations

Revision ID: 17e7ac7edc40
Revises: e3ff2ea2c840
Create Date: 2026-03-19 17:02:13.029083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17e7ac7edc40'
down_revision: Union[str, Sequence[str], None] = 'e3ff2ea2c840'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('translations', sa.Column('is_valid', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('translations', 'is_valid')
    # ### end Alembic commands ###
