"""empty message

Revision ID: 1cf8bee04954
Revises: 126487d850b4
Create Date: 2025-10-26 11:19:20.667632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cf8bee04954'
down_revision: Union[str, Sequence[str], None] = '126487d850b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets', 'size_bytes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('definitions', sa.Column('text', sa.String(), server_default='', nullable=False))
    op.create_index(op.f('ix_definitions_text'), 'definitions', ['text'], unique=False)
    op.drop_index(op.f('ix_text_definitions_text'), table_name='text_definitions')
    op.drop_column('text_definitions', 'text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('text_definitions', sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_text_definitions_text'), 'text_definitions', ['text'], unique=False)
    op.drop_index(op.f('ix_definitions_text'), table_name='definitions')
    op.drop_column('definitions', 'text')
    op.alter_column('assets', 'size_bytes',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
