"""empty message

Revision ID: 219e86744063
Revises: e4f7ceb74051
Create Date: 2025-07-27 16:38:45.972006

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "219e86744063"
down_revision: Union[str, Sequence[str], None] = "e4f7ceb74051"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "role",
            sa.Enum("ADMIN", "USER", name="userrole"),
            server_default=sa.text("'USER'"),
            nullable=False,
        ),
    )
    op.execute("UPDATE users SET auth_provider = UPPER(auth_provider);")
    op.alter_column(
        "users",
        "auth_provider",
        existing_type=sa.VARCHAR(),
        type_=sa.Enum("GOOGLE", "EMAIL", name="authprovider"),
        postgresql_using="auth_provider::authprovider",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "auth_provider",
        existing_type=sa.Enum("GOOGLE", "EMAIL", name="authprovider"),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.drop_column("users", "role")
    # ### end Alembic commands ###
