"""add context to translations

Revision ID: 24ae86d0b547
Revises: 9108e6a9a626
Create Date: 2026-03-15 19:30:54.857649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24ae86d0b547'
down_revision: Union[str, Sequence[str], None] = '9108e6a9a626'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('translations', sa.Column('context', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('translations', 'context')
    # ### end Alembic commands ###
