"""empty message

Revision ID: 2b06ce34cb93
Revises: bd9d5955f334
Create Date: 2025-09-01 17:30:06.991794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b06ce34cb93'
down_revision: Union[str, Sequence[str], None] = 'bd9d5955f334'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_levels_name'), table_name='levels')
    op.create_index(op.f('ix_levels_name'), 'levels', ['name'], unique=False)
    op.create_unique_constraint(None, 'levels', ['value'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'levels', type_='unique')
    op.drop_index(op.f('ix_levels_name'), table_name='levels')
    op.create_index(op.f('ix_levels_name'), 'levels', ['name'], unique=True)
    # ### end Alembic commands ###
