"""empty message

Revision ID: 34fcdb578b5f
Revises: 6bd1e3c11a74
Create Date: 2025-08-20 15:39:04.083321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34fcdb578b5f'
down_revision: Union[str, Sequence[str], None] = '6bd1e3c11a74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['image_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('definitions_image')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('definitions_image',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['definitions.id'], name=op.f('definitions_image_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['image_id'], ['assets.id'], name=op.f('definitions_image_image_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('definitions_image_pkey'))
    )
    op.drop_table('image_definitions')
    # ### end Alembic commands ###
