"""empty message

Revision ID: 4be0a1395dd9
Revises: a8568815ed59
Create Date: 2026-03-05 15:12:42.435714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4be0a1395dd9'
down_revision: Union[str, Sequence[str], None] = 'a8568815ed59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("UPDATE text_definitions SET language = 'ES' WHERE language IS NULL")
    op.execute("UPDATE meanings SET language = 'ES' WHERE language IS NULL")
    op.alter_column('meanings', 'language',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'ES'::character varying"))
    op.alter_column('meanings', 'language', server_default=None)
    op.alter_column('text_definitions', 'language',
               existing_type=sa.VARCHAR(),
               nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('text_definitions', 'language',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('meanings', 'language',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'ES'::character varying"))
    # ### end Alembic commands ###
