"""empty message

Revision ID: 6bd1e3c11a74
Revises: 87d29ee5dcee
Create Date: 2025-08-20 15:38:36.192725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bd1e3c11a74'
down_revision: Union[str, Sequence[str], None] = '87d29ee5dcee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('definitions_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['image_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('text_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_text_definitions_text'), 'text_definitions', ['text'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_text_definitions_text'), table_name='text_definitions')
    op.drop_table('text_definitions')
    op.drop_table('definitions_image')
    # ### end Alembic commands ###
