"""replace issue_types table with enum

Revision ID: 6db4eff50d8c
Revises: f96d0f67e12e
Create Date: 2026-03-07 10:22:36.699509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6db4eff50d8c'
down_revision: Union[str, Sequence[str], None] = 'f96d0f67e12e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("DELETE FROM issues")
    op.drop_constraint(op.f('issues_type_id_fkey'), 'issues', type_='foreignkey')
    op.drop_column('issues', 'type_id')
    op.add_column('issues', sa.Column('type', sa.String(), nullable=False))
    op.drop_index(op.f('ix_issue_types_name'), table_name='issue_types')
    op.drop_table('issue_types')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('type_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('issues_type_id_fkey'), 'issues', 'issue_types', ['type_id'], ['id'], ondelete='SET NULL')
    op.drop_column('issues', 'type')
    op.create_table('issue_types',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('issue_types_pkey'))
    )
    op.create_index(op.f('ix_issue_types_name'), 'issue_types', ['name'], unique=False)
    # ### end Alembic commands ###
