"""add context to translation unique constraint

Revision ID: 7bff08ae18ea
Revises: 17e7ac7edc40
Create Date: 2026-03-19 18:08:31.230857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bff08ae18ea'
down_revision: Union[str, Sequence[str], None] = '17e7ac7edc40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE translations SET context = '' WHERE context IS NULL")
    op.alter_column('translations', 'context',
               existing_type=sa.VARCHAR(),
               server_default='',
               nullable=False)
    op.drop_constraint(op.f('uq_translations_text_langs'), 'translations', type_='unique')
    op.create_unique_constraint('uq_translations_text_langs', 'translations', ['text', 'lang_from', 'lang_to', 'context'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_translations_text_langs', 'translations', type_='unique')
    op.create_unique_constraint(op.f('uq_translations_text_langs'), 'translations', ['text', 'lang_from', 'lang_to'], postgresql_nulls_not_distinct=False)
    op.alter_column('translations', 'context',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
