"""empty message

Revision ID: 80e9bd70e171
Revises: ea728b68cde2
Create Date: 2026-02-25 19:58:49.390887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80e9bd70e171'
down_revision: Union[str, Sequence[str], None] = 'ea728b68cde2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('definitions', sa.Column('group', sa.String(), nullable=True))
    op.create_index(op.f('ix_definitions_group'), 'definitions', ['group'], unique=False)
    op.drop_index(op.f('ix_text_definitions_group'), table_name='text_definitions')
    op.drop_column('text_definitions', 'group')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('text_definitions', sa.Column('group', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_text_definitions_group'), 'text_definitions', ['group'], unique=False)
    op.drop_index(op.f('ix_definitions_group'), table_name='definitions')
    op.drop_column('definitions', 'group')
    # ### end Alembic commands ###
