"""empty message

Revision ID: 81865411847e
Revises: 3587df6c535e
Create Date: 2026-03-04 19:58:38.324505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81865411847e'
down_revision: Union[str, Sequence[str], None] = '3587df6c535e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('language', sa.String(), server_default='ES', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'language')
    # ### end Alembic commands ###
