"""empty message

Revision ID: 8771d7a6681e
Revises: 81865411847e
Create Date: 2026-03-05 15:08:35.191550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8771d7a6681e'
down_revision: Union[str, Sequence[str], None] = '81865411847e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('text_definitions', sa.Column('language', sa.String(), server_default='ES', nullable=True))
    op.execute("""
        UPDATE text_definitions
        SET language = definitions.language
        FROM definitions
        WHERE text_definitions.id = definitions.id
    """)
    op.drop_column('definitions', 'language')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('text_definitions', 'language')
    op.add_column('definitions', sa.Column('language', sa.VARCHAR(), server_default=sa.text("'ES'::character varying"), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
