"""add definition_group to questions

Revision ID: 9108e6a9a626
Revises: c2344215c25f
Create Date: 2026-03-10 15:46:54.238627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9108e6a9a626'
down_revision: Union[str, Sequence[str], None] = 'c2344215c25f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('questions', sa.Column('definition_group', sa.String(), nullable=True))
    op.execute("""
        UPDATE questions
        SET definition_group = d."group"
        FROM definitions d
        WHERE d.id = questions.correct_definition_id
    """)
    op.alter_column('questions', 'definition_group', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'definition_group')
    # ### end Alembic commands ###
