"""empty message

Revision ID: 9240e7effe56
Revises: 12580170c616
Create Date: 2026-02-18 14:06:56.907197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9240e7effe56'
down_revision: Union[str, Sequence[str], None] = '12580170c616'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('target_language', sa.Enum('EN', 'ES', name='targetlanguagecode'), server_default='ES', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'target_language')
    # ### end Alembic commands ###
