"""empty message

Revision ID: 927e3ac427b7
Revises: 929a79264778
Create Date: 2025-08-20 20:12:43.122222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '927e3ac427b7'
down_revision: Union[str, Sequence[str], None] = '929a79264778'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('type', sa.Enum('TEXT', 'IMAGE', name='questiontypename'), nullable=False))
    op.create_index(op.f('ix_questions_type'), 'questions', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questions_type'), table_name='questions')
    op.drop_column('questions', 'type')
    # ### end Alembic commands ###
