"""replace issue_statuses table with enum

Revision ID: 9640d98c18e9
Revises: 6db4eff50d8c
Create Date: 2026-03-07 11:17:46.759543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9640d98c18e9'
down_revision: Union[str, Sequence[str], None] = '6db4eff50d8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("DELETE FROM issues")
    op.drop_constraint(op.f('issues_status_id_fkey'), 'issues', type_='foreignkey')
    op.drop_column('issues', 'status_id')
    op.add_column('issues', sa.Column('status', sa.String(), nullable=False))
    op.drop_index(op.f('ix_issue_statuses_name'), table_name='issue_statuses')
    op.drop_table('issue_statuses')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('issues_status_id_fkey'), 'issues', 'issue_statuses', ['status_id'], ['id'], ondelete='SET NULL')
    op.drop_column('issues', 'status')
    op.create_table('issue_statuses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('issue_statuses_pkey')),
    sa.UniqueConstraint('value', name=op.f('issue_statuses_value_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_issue_statuses_name'), 'issue_statuses', ['name'], unique=False)
    # ### end Alembic commands ###
