"""empty message

Revision ID: a44802027f6c
Revises: 254bfa1a305b
Create Date: 2025-10-20 15:45:52.134616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a44802027f6c'
down_revision: Union[str, Sequence[str], None] = '254bfa1a305b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issue_statuses', sa.Column('value', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'issue_statuses', ['value'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'issue_statuses', type_='unique')
    op.drop_column('issue_statuses', 'value')
    # ### end Alembic commands ###
