"""empty message

Revision ID: a521e26955df
Revises: a44802027f6c
Create Date: 2025-10-20 15:47:28.914458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a521e26955df'
down_revision: Union[str, Sequence[str], None] = 'a44802027f6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('issue_statuses', 'value',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('issue_statuses', 'value',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
