"""add language to categories

Revision ID: a73ef62389c0
Revises: 9640d98c18e9
Create Date: 2026-03-08 11:43:36.938289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a73ef62389c0'
down_revision: Union[str, Sequence[str], None] = '9640d98c18e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('language', sa.String(), server_default='EN', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'language')
    # ### end Alembic commands ###
