"""add translated_at to translations

Revision ID: b6a4337cc2ee
Revises: f5a408035b95
Create Date: 2026-03-08 13:19:02.562724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6a4337cc2ee'
down_revision: Union[str, Sequence[str], None] = 'f5a408035b95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('translations', sa.Column('translated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('translations', 'translated_at')
    # ### end Alembic commands ###
