"""empty message

Revision ID: bf1bde9d2f9f
Revises: 1cf8bee04954
Create Date: 2025-10-31 10:20:11.458418

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bf1bde9d2f9f"
down_revision: Union[str, Sequence[str], None] = "1cf8bee04954"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(sa.text("TRUNCATE TABLE translations RESTART IDENTITY"))

    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_translations_context"), table_name="translations")
    op.create_unique_constraint(
        "uq_translations_text_langs", "translations", ["text", "lang_from", "lang_to"]
    )
    op.drop_column("translations", "context")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "translations",
        sa.Column("context", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_constraint("uq_translations_text_langs", "translations", type_="unique")
    op.create_index(
        op.f("ix_translations_context"), "translations", ["context"], unique=False
    )
    # ### end Alembic commands ###
