"""remove level_id from meanings

Revision ID: c2344215c25f
Revises: b6a4337cc2ee
Create Date: 2026-03-08 16:28:01.449538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2344215c25f'
down_revision: Union[str, Sequence[str], None] = 'b6a4337cc2ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('meanings_level_id_fkey'), 'meanings', type_='foreignkey')
    op.drop_column('meanings', 'level_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meanings', sa.Column('level_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('meanings_level_id_fkey'), 'meanings', 'levels', ['level_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
