"""empty message

Revision ID: cdcfab3e00de
Revises: 2394f928752b
Create Date: 2025-09-06 15:57:01.254298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cdcfab3e00de'
down_revision: Union[str, Sequence[str], None] = '2394f928752b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets', 'status',
               existing_type=postgresql.ENUM('PENDING', 'READY', 'failed', 'FAILED', name='assetstatus'),
               type_=sa.Enum('PENDING', 'READY', 'FAILED', name='assetstatus', native_enum=False),
               existing_nullable=False)
    op.alter_column('image_definitions', 'image_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('image_definitions_image_id_fkey'), 'image_definitions', type_='foreignkey')
    op.create_foreign_key(None, 'image_definitions', 'assets', ['image_id'], ['id'], ondelete='SET NULL')
    op.add_column('meanings', sa.Column('audio_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'meanings', 'assets', ['audio_id'], ['id'], ondelete='SET NULL')
    op.add_column('text_definitions', sa.Column('audio_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'text_definitions', 'assets', ['audio_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'text_definitions', type_='foreignkey')
    op.drop_column('text_definitions', 'audio_id')
    op.drop_constraint(None, 'meanings', type_='foreignkey')
    op.drop_column('meanings', 'audio_id')
    op.drop_constraint(None, 'image_definitions', type_='foreignkey')
    op.create_foreign_key(op.f('image_definitions_image_id_fkey'), 'image_definitions', 'assets', ['image_id'], ['id'], ondelete='CASCADE')
    op.alter_column('image_definitions', 'image_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('assets', 'status',
               existing_type=sa.Enum('PENDING', 'READY', 'FAILED', name='assetstatus', native_enum=False),
               type_=postgresql.ENUM('PENDING', 'READY', 'failed', 'FAILED', name='assetstatus'),
               existing_nullable=False)
    # ### end Alembic commands ###
