"""empty message

Revision ID: d872cf896c08
Revises: b58a33eab0f5
Create Date: 2026-02-22 10:08:14.992278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd872cf896c08'
down_revision: Union[str, Sequence[str], None] = 'b58a33eab0f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('text_definitions', sa.Column('group', sa.String(), nullable=True))
    op.create_index(op.f('ix_text_definitions_group'), 'text_definitions', ['group'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_text_definitions_group'), table_name='text_definitions')
    op.drop_column('text_definitions', 'group')
    # ### end Alembic commands ###
