"""empty message

Revision ID: ea728b68cde2
Revises: e19ee131b1ef
Create Date: 2026-02-22 12:00:23.616006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea728b68cde2'
down_revision: Union[str, Sequence[str], None] = 'e19ee131b1ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_definitions_category_id'), 'definitions', ['category_id'], unique=False)
    op.create_index(op.f('ix_definitions_level_id'), 'definitions', ['level_id'], unique=False)
    op.create_index(op.f('ix_definitions_meanings_meaning_id'), 'definitions_meanings', ['meaning_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_definitions_meanings_meaning_id'), table_name='definitions_meanings')
    op.drop_index(op.f('ix_definitions_level_id'), table_name='definitions')
    op.drop_index(op.f('ix_definitions_category_id'), table_name='definitions')
    # ### end Alembic commands ###
