"""empty message

Revision ID: efbeab575ebb
Revises: 4be0a1395dd9
Create Date: 2026-03-05 15:45:35.647769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efbeab575ebb'
down_revision: Union[str, Sequence[str], None] = '4be0a1395dd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('definitions', sa.Column('language', sa.String(), nullable=True))
    op.execute("""
        UPDATE definitions
        SET language = text_definitions.language
        FROM text_definitions
        WHERE definitions.id = text_definitions.id
    """)
    op.drop_column('text_definitions', 'language')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('text_definitions', sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('definitions', 'language')
    # ### end Alembic commands ###
