"""empty message

Revision ID: f16cb3e8e935
Revises: cdcfab3e00de
Create Date: 2025-09-06 22:34:57.712193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f16cb3e8e935'
down_revision: Union[str, Sequence[str], None] = 'cdcfab3e00de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_assets_file_key'), 'assets', ['file_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assets_file_key'), table_name='assets')
    # ### end Alembic commands ###
