"""add language to levels

Revision ID: f5a408035b95
Revises: 3bf66e842243
Create Date: 2026-03-08 12:05:13.256122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5a408035b95'
down_revision: Union[str, Sequence[str], None] = '3bf66e842243'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('levels', sa.Column('language', sa.String(), server_default='EN', nullable=False))
    op.alter_column('levels', 'language', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('levels', 'language')
    # ### end Alembic commands ###
