"""empty message

Revision ID: f96d0f67e12e
Revises: efbeab575ebb
Create Date: 2026-03-05 16:10:44.935904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f96d0f67e12e'
down_revision: Union[str, Sequence[str], None] = 'efbeab575ebb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("UPDATE definitions SET language = 'ES' WHERE language IS NULL")
    op.alter_column('definitions', 'language',
               existing_type=sa.VARCHAR(),
               nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('definitions', 'language',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
