name: Deploy to Server

on:
  push:
    branches:
      - master

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: vitalyionov
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: true
          target: prod
          tags: |
            ghcr.io/vitalyionov/learn-language-server:latest
            ghcr.io/vitalyionov/learn-language-server:${{ github.sha }}

      - name: Prepare docker-compose.yml
        run: cp docker-compose.prod.yml docker-compose.yml

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "docker-compose.yml,nginx/conf.d/prod.conf"
          target: /opt/learn-language/
          overwrite: true
          tar_exec: tar
        env:
          TAR_OPTIONS: --no-same-owner --no-same-permissions

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /opt/learn-language
            echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u vitalyionov --password-stdin
            
            tail -c1 .env | tr -d '\n' | grep -q '^$' || echo >> .env

            SHA="${{ github.sha }}"
            if grep -q '^IMAGE_TAG=' .env; then
              sed -i 's/^IMAGE_TAG=.*/IMAGE_TAG='"$SHA"'/g' .env
            else
              printf 'IMAGE_TAG=%s\n' "$SHA" >> .env
            fi
      
            docker compose pull
            docker compose up -d db
            
            echo "Waiting for Postgres to be healthy..."
              for i in $(seq 1 60); do
                CID="$(docker compose ps -q db || true)"
                if [ -n "${CID}" ]; then
                  STATUS="$(docker inspect -f '{{.State.Health.Status}}' "${CID}" 2>/dev/null || echo unknown)"
                  if [ "${STATUS}" = "healthy" ]; then
                    echo "Postgres is healthy."
                    break
                  fi
                fi
                sleep 2
                if [ "$i" -eq 60 ]; then
                  echo "Postgres did not become healthy in time"
                  docker compose logs --no-color db | tail -n 200 || true
                  exit 1
                fi
              done
      
            docker compose run --rm -e PYTHONPATH=/app web \
              sh -lc 'alembic -c /app/alembic.ini upgrade head -v'
            docker compose up -d --no-deps --force-recreate
            docker compose run --rm -e PYTHONPATH=/app web \
              sh -lc 'alembic -c /app/alembic.ini current || true'
            docker system prune -f

      - name: Telegram notify
        if: ${{ always() }}
        uses: appleboy/telegram-action@v1.0.1
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          disable_web_page_preview: true
          message: |
            ${{ job.status == 'success' && '✅' || '❌' }} Deploy *${{ job.status }}* for *${{ github.repository }}*
            *Branch:* ${{ github.ref_name }}
            *Commit:* ${{ github.sha }}
            [Action](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})